services:

  accesslog:
    image: diamol/ch04-access-log:2e
    networks:
      - app-net

  iotd:
    image: diamol/ch04-image-of-the-day:2e
    ports:
      - "80"
    networks:
      - app-net

  image-gallery:
    image: diamol/ch04-image-gallery:2e
    ports:
      - "8010:80" 
    depends_on:
      - accesslog
      - iotd
    networks:
      - app-net

networks:
  app-net:
    name: nat
    external: true